### ISSUE TITLE
Invalid `ACEStransformID`

### ISSUE THREAD

**Issue by KelSolaar** [ampas/aces-output#4]
Hello,

As discussed on Slack, I'm preparing the https://github.com/AcademySoftwareFoundation/OpenColorIO-Config-ACES generator for ACES 2.0 and I found out the following issues for the Input and CSC  `ACEStransformID`:

- [x] `urn:ampas:aces:transformId:v2.0:ODT.Academy.P3D60.a2.v1` is using invalid `ODT` type instead of `Output`!
- [x] `urn:ampas:aces:transformId:v2.0:ODT.Academy.P3DCI_D60sim.a2.v1` is using invalid `ODT` type instead of `Output`!
- [x] `urn:ampas:aces:transformId:v2.0:ODT.Academy.P3D65.a2.v1` is using invalid `ODT` type instead of `Output`!
- [x] `urn:ampas:aces:transformId:v2.0:ODT.Academy.P3D65_Rec709limited.a2.v1` is using invalid `ODT` type instead of `Output`!
- [x] `urn:ampas:aces:transformId:v2.0:ODT.Academy.P3DCI_D65sim.a2.v1` is using invalid `ODT` type instead of `Output`!
- [x] `urn:ampas:aces:transformId:v2.0:ODT.Academy.P3D65_D60sim.a2.v1` is using invalid `ODT` type instead of `Output`!
- [x] `urn:ampas:aces:transformId:v2.0:ODT.Academy.P3D65_108nit.a2.v1` is using invalid `ODT` type instead of `Output`!
- [x] `urn:ampas:aces:transformId:v2.0:Output.Academy.DisplayP3.a2.v1` is duplicated!
- [x] `urn:ampas:aces:transformId:v2.0:Output.Academy.Rec2020_ST2084_P3D65limited_1000nit.a2.v1` is duplicated!

I will update the thread if I come across new ones.

Cheers,

Thomas

**Comment by thomasmansencal** [comment]
Thanks @scottdyer!
