### ISSUE TITLE
TransformIDs in Rec2020-HDR transforms are inconsistent

### ISSUE THREAD

**Issue by scottdyer** [ampas/aces-output#6]
The filenames all include `ST2084` but that is not in all of the TransformIDs and the Username structure varies from transform to transform.

**Comment by nick-shaw** [comment]
As discussed during [meeting #156](https://paper.dropbox.com/doc/Meeting-Summaries--CRWFAWNQqGWCzhhUJjnHto4lAg-AmweeevBcufkcozYLHlG3#:uid=538629294145705187676348&h2=Meeting-Notes), the ideal would be to have a procedurally generated ACES Transform ID (and description?) based on the parameters passed to the 'super-transform' macro. But we pass chomaticity coordinates, not colour space names or enums. So how do we deal with that? We can look up standard sets, such as Rec.709, Rec.2020 and P3, and convert them to names. But how would we deal with generating a transform ID for a custom set of primaries? Or would those be considered non-standard, and not get a transform ID?

**Comment by scottdyer** [comment]
All names have been updated to Rec.2100 in the [dev-release-rc2-staging branch](https://github.com/ampas/aces-output/tree/v2-dev-release-staging)
