### ISSUE TITLE
Should the linear scale factor be 48/100 instead of 0.5?

### ISSUE THREAD

**Issue by nick-shaw** [ampas/aces-output#8]
https://github.com/ampas/aces-output/blob/e22e58ee16068d4346bf857137e89fe96fc2a11d/p3-hdr/Output.Academy.P3D65_ST2084_108nit.ctl#L64

I know the theatrical 2.6 gamma encodings are relative, not absolute, but to make things completely consistent, would it be better to say that for a theatrical environment you should use a `peakLuminance` that is `100 / 48` times the target peak?

That way SDR cinema would use `peakLuminance = 48 * 100/48 = 100`

Dolby Cinema would use `peakLuminance = 108 * 100/48 = 225`

and DCI HDR would use `peakLuminance = 300 * 100/48 = 625`

**Comment by scottdyer** [comment]
This has been implemented in the [dev-release-rc2-staging branch](https://github.com/ampas/aces-output/tree/v2-dev-release-staging)
