### ISSUE TITLE
Inconsistent use of underscores in transform IDs

### ISSUE THREAD

**Issue by nick-shaw** [ampas/aces-output#9]
https://github.com/ampas/aces-output/blob/e22e58ee16068d4346bf857137e89fe96fc2a11d/srgb/Output.Academy.sRGB_Gamma_2pt2.ctl#L2

The sRGB Gamma 2.2 transform uses `Gamma_2pt2` to define the EOTF. In the [spreadsheet](https://docs.google.com/spreadsheets/d/1ZttIFJKOE7WAgceFFSrDc34JegjD3loGZWIZGPCKzQs/edit?usp=sharing) `Gamma2pt2` is used, which makes more sense, since underscores are used to separate attributes.

**Comment by scottdyer** [comment]
All transform IDs have been updated on the [dev-release-rc2-staging branch](https://github.com/ampas/aces-output/tree/v2-dev-release-staging)
